export const initState = {
  userAccount: {
    firstName: null,
    lastName: null,
    email: null,
    password: null,
    ownesCompany: null,
    _id: null,
  },
  jobPosts: [],
  jobPostDetails: {
    job: {
      requiredSkills: [],
      responsabilities: [],
      advantages: [],
      _id: null,
      catagory: null,
      jobTitle: null,
      jobDescription: null,
      salary: null,
      location: null,
      JobOwner: null,
      companyName: null,
      createdAt: null,
      updatedAt: null,
      __v: 0,
    },
    companyInfo: {
      _id: null,
      companyName: null,
      description: null,
      location: null,
      owner: null,
      createdAt: null,
      updatedAt: null,
      __v: 0,
    },
  },
  error: {},
};
